#!/bin/bash

ENV=$1
echo $ENV
pushd $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
INSTALLDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

echo "Creating tmp directory"
mkdir -p "tmp"

install_from_github() {
    # $1 is of the form: robbyrussell/oh-my-zsh
    REPO=$(echo $1 | cut -d '/' -f 2)
        echo "Cloning https://github.com/$1"
        git clone  "https://github.com/$1.git" "./tmp/$REPO"
}

# Run scripts
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/sindresorhus/pure.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/pure
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
curl -o ~/.config/kitty/palenight.conf https://raw.githubusercontent.com/citizen428/kitty-palenight/master/palenight.conf

./makelinks

# Command Line Fuzzy Finder
# install_from_github "junegunn/fzf"
# fzf-master/install --bin

# tmux Plugin Manager
# mkdir -p "$HOME/.tmux/plugins"
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

ls
echo "Deleting tmp dir"
rm -rf ./tmp

popd
