#!/bin/bash

echo "CREATING SYMLINKS"

DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOTFILES_TMP="$DOTFILES_DIR/tmp"
# HOMEDIR=$( getent passwd "$SUDO_USER" | cut -d: -f6 )

symlink() {
  rm -f $2 || true
  ln -sv $1 $2 || true
}

tryMkdir() {
  mkdir -p $1 || true
}

# vim
symlink "$DOTFILES_DIR/vim/vimrc" "$HOME/.vimrc"
tryMkdir "$HOME/.config/nvim"
symlink "$DOTFILES_DIR/vim/init.vim" "$HOME/.config/nvim/init.vim"

# zsh
symlink "$DOTFILES_DIR/zsh/zshrc" "$HOME/.zshrc"
tryMkdir "$HOME/.config/kitty"
symlink "$DOTFILES_DIR/shell/kitty.conf" "$HOME/.config/kitty/kitty.conf"
symlink "$DOTFILES_DIR/shell/challenger-deep.conf" "$HOME/.config/kitty/challenger-deep.conf"

# git
# symlink "$DOTFILES_DIR/.gitconfig" "$HOME/.gitconfig"
# symlink "$DOTFILES_DIR/.gitignore_global" "$HOME/.gitignore_global"

# tmux
# tryMkdir "$HOME/.tmux/plugins"
symlink "$DOTFILES_DIR/tmux.conf" "$HOME/.tmux.conf"
